### PR TITLE
Adding solution of Array Manipulation.

### PR DESCRIPTION
**Pull request by maanpatel2492**
Adding a solution of Array Manipulation in c++.

### CODE REVIEW

**Comment by TechnoBlogger14o3** [comment]
@maanpatel2492 Please do create a separate branch, or atleast put them in their respective folders. 
I've created 3 Easy, Medium and hard.

**Comment by TechnoBlogger14o3** [comment]
@maanpatel2492 Please create a separate branch, or atleast please keep the file in their respective folders.

**Comment by maanpatel2492** [comment]
ohh sorry for the mistake.
I will put files in the respective folders from now onwards.
Is it ok?

**Comment by TechnoBlogger14o3** [comment]
@maanpatel2492 
If possible do for previous ones also, otherwise the repo will not look good.
Thanks

**Pull request closed without merging**
